/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconsClose: typeof import('./../src/components/Icons/Close.vue')['default']
    IconsMaximize: typeof import('./../src/components/Icons/Maximize.vue')['default']
    IconsMinimize: typeof import('./../src/components/Icons/Minimize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WindowsTitleBar: typeof import('./../src/components/Windows/TitleBar.vue')['default']
  }
}
